# -*- coding: utf-8 -*-
"""Day1-miniproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11LDwz3Vo5psfWtNT9O9Es5yPeYkxy1h0
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("student_data.csv")

print(df.head())

print("=" * 50)
print("        STUDENT PERFORMANCE EXPLORER")
print("=" * 50)

print("\n📌 DATASET OVERVIEW")
print("-" * 50)

total_students = len(df)
total_columns = len(df.columns)
unique_departments = df["department"].nunique()

print(f"Total Number of Students : {total_students}")
print(f"Total Number of Columns  : {total_columns}")
print(f"Unique Departments       : {unique_departments}")

print("\n📌 DEPARTMENT WISE ANALYSIS")
print("-" * 50)

department_count = df["department"].value_counts()

for dept, count in department_count.items():
    print(f"{dept} : {count} students")

print("\n📌 SCORE ANALYSIS")
print("-" * 50)

highest_math = df["math_score"].max()
lowest_math = df["math_score"].min()
avg_math = df["math_score"].mean()
avg_programming = df["programming_score"].mean()
avg_attendance = df["attendance_percentage"].mean()

print(f"Highest Math Score        : {highest_math}")
print(f"Lowest Math Score         : {lowest_math}")
print(f"Average Math Score        : {avg_math:.2f}")
print(f"Average Programming Score : {avg_programming:.2f}")
print(f"Average Attendance        : {avg_attendance:.2f}%")

print("\n📌 GENDER WISE ANALYSIS")
print("-" * 50)

gender_avg = df.groupby("gender")["total_score"].mean()

for gender, avg_score in gender_avg.items():
    print(f"{gender} Average Total Score : {avg_score:.2f}")

print("\n📌 TOP 5 PERFORMERS")
print("-" * 50)

top_students = df.sort_values(by="total_score", ascending=False).head(5)

for index, row in top_students.iterrows():
    print(f"Name       : {row['name']}")
    print(f"Department : {row['department']}")
    print(f"Total Score: {row['total_score']}")
    print("-" * 30)

print("\n📌 ATTENDANCE ANALYSIS")
print("-" * 50)

low_attendance = df[df["attendance_percentage"] < 75]

if len(low_attendance) > 0:
    for index, row in low_attendance.iterrows():
        print(f"Name       : {row['name']}")
        print(f"Department : {row['department']}")
        print(f"Attendance : {row['attendance_percentage']}%")
        print("-" * 30)
else:
    print("All students have attendance above 75%.")

print("\n" + "=" * 50)
print("        REPORT GENERATED SUCCESSFULLY")
print("=" * 50)