# -*- coding: utf-8 -*-
"""Day1-practiceQuestions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/161_o4vVFPDasSB8GR9uA7fc6goCIS6fW
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("student_data.csv")

electronics_students = df[df["department"] == "ECE"]

print("Number of students from Electronics Department:")
print(len(electronics_students))

female_attendance = df[df["gender"] == "Female"]["attendance_percentage"].mean()

print("Average attendance of female students:")
print(f"{female_attendance:.2f}%")

lowest_programming = df["programming_score"].min()

student_lowest_programming = df[df["programming_score"] == lowest_programming]

print("Student with the lowest programming score:")

for index, row in student_lowest_programming.iterrows():
    print(f"Name : {row['name']}")
    print(f"Programming Score : {row['programming_score']}")

students_above_80 = df[df["math_score"] > 80]

print("Number of students who scored above 80 in math:")
print(len(students_above_80))

high_attendance_avg = df[df["attendance_percentage"] > 90]["total_score"].mean()

print("Average total score for students with attendance above 90%:")
print(f"{high_attendance_avg:.2f}")