# -*- coding: utf-8 -*-
"""Day2-MiniProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gW35wA6M9b6Zue4UHSd9kRL1_fv2vaHZ
"""

#SQL QUERY
import pandas as pd
import sqlite3
import matplotlib.pyplot as plt
df = pd.read_csv("student_performance.csv")
conn = sqlite3.connect(":memory:")
df.to_sql("students", conn, index=False, if_exists="replace")

#Panel 1 Data : Average Math Score by Department
query1 = """
SELECT department,
AVG(math_score) AS avg_math_score
FROM students
GROUP BY department
"""

panel1 = pd.read_sql_query(query1, conn)

print(panel1)

#Panel 2 Data : Student Count by Department
query2 = """
SELECT department,
COUNT(*) AS student_count
FROM students
GROUP BY department
"""

panel2 = pd.read_sql_query(query2, conn)

print(panel2)

#Panel 3 Data : Top 8 Students by Total Score
df["total_score"] = df["math_score"] + df["programming_score"]
df.to_sql("students", conn, index=False, if_exists="replace")
query3 = """
SELECT name,
department,
total_score
FROM students
ORDER BY total_score DESC
LIMIT 8
"""
panel3 = pd.read_sql_query(query3, conn)
print(panel3)

#Panel 4 Data : Gender-wise Average Attendance
query4 = """
SELECT gender,
AVG(attendance_percentage) AS avg_attendance
FROM students
GROUP BY gender
"""

panel4 = pd.read_sql_query(query4, conn)

print(panel4)

#MATPLOTLIB VISUALIZATION
#Panel 1 : Average Math Score by Department - BAR Chart
plt.figure(figsize=(7, 5))

plt.bar(panel1["department"], panel1["avg_math_score"])

plt.title("Average Math Score by Department")
plt.xlabel("Department")
plt.ylabel("Average Math Score")

plt.show()

#Panel 2 : Student Count Pie Chart
plt.figure(figsize=(7, 5))

plt.pie(
    panel2["student_count"],
    labels=panel2["department"],
    autopct="%1.1f%%"
)

plt.title("Student Count by Department")

plt.show()

#Panel 3 : Top 8 Students Horizontal Bar Chart
plt.figure(figsize=(8, 5))

plt.barh(
    panel3["name"],
    panel3["total_score"]
)

plt.title("Top 8 Students by Total Score")
plt.xlabel("Total Score")
plt.ylabel("Student Name")

plt.show()

#Panel 4 : Gender-wise Average Attendance Bar Chart
plt.figure(figsize=(7, 5))

plt.bar(
    panel4["gender"],
    panel4["avg_attendance"]
)

plt.title("Gender-wise Average Attendance")
plt.xlabel("Gender")
plt.ylabel("Average Attendance")

plt.show()