# -*- coding: utf-8 -*-
"""Day2-Practice Questions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tv8PCXk7YOsQKGbGMKYeogdARtgb2GC9
"""

import pandas as pd
import sqlite3
import matplotlib.pyplot as plt
df = pd.read_csv("student_performance.csv")
print(df.head())
conn = sqlite3.connect(":memory:")
df.to_sql("students", conn, index=False, if_exists="replace")

#1.SQL query to find the average programming score for female students only
query = """
SELECT AVG(programming_score) AS avg_programming_score
FROM students
WHERE gender = 'Female'
"""

result = pd.read_sql_query(query, conn)

print(result)

#2.WHERE Example
query2_where = """
SELECT *
FROM students
WHERE math_score > 80
"""

result2_where = pd.read_sql_query(query2_where, conn)

print(result2_where)

#2.HAVING Example
query2_having = """
SELECT department,
AVG(math_score) AS avg_math
FROM students
GROUP BY department
HAVING AVG(math_score) > 80
"""

result2_having = pd.read_sql_query(query2_having, conn)

print(result2_having)

#3.Departments with Average Attendance Above 85%
query3 = """
SELECT department,
AVG(attendance_percentage) AS avg_attendance
FROM students
GROUP BY department
HAVING AVG(attendance_percentage) > 85
"""

result3 = pd.read_sql_query(query3, conn)

print(result3)

#4.pd.read_sql_query() Return Type
query4 = "SELECT * FROM students"

result4 = pd.read_sql_query(query4, conn)

print(type(result4))

#5.SQL Query for Average Programming Score by Department
query5 = """
SELECT department,
AVG(programming_score) AS avg_programming
FROM students
GROUP BY department
"""

programming_chart = pd.read_sql_query(query5, conn)

print(programming_chart)

#5.Bar Chart for Average Programming Scores
plt.figure(figsize=(7, 5))

plt.bar(
    programming_chart["department"],
    programming_chart["avg_programming"]
)

plt.title("Average Programming Score by Department")
plt.xlabel("Department")
plt.ylabel("Average Programming Score")

plt.show()