# -*- coding: utf-8 -*-
"""Day4-PracticeQuestions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1avc8m9vP6-MEwHU9y-fTD77DjO0943Zu
"""

big_data_5vs = {
    "Volume": "Flipkart processes millions of orders during sales",
    "Velocity": "Real-time order updates every second",
    "Variety": "Text, Images, Videos, JSON, GPS",
    "Veracity": "Detecting fake or fraudulent transactions",
    "Value": "Generating sales insights and recommendations"
}

for v, example in big_data_5vs.items():
    print(f"{v} : {example}")

"""It appears the `large_sales_data.csv` file was not found, causing an `AnalysisException`. To proceed, I'll create a dummy CSV file with some sample data."""

import pandas as pd
import numpy as np

# Generate dummy data
np.random.seed(42)
data = {
    'product_id': np.arange(100),
    'revenue': np.random.randint(10000, 100000, 100),
    'city': np.random.choice(['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'], 100)
}
df_dummy = pd.DataFrame(data)

# Save to a CSV file
df_dummy.to_csv('large_sales_data.csv', index=False)
print('Created dummy large_sales_data.csv with 100 rows.')

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("TransformationAction").getOrCreate()

df = spark.read.csv("large_sales_data.csv", header=True, inferSchema=True)

# Transformation (Lazy)
filtered_df = df.filter(df.revenue > 50000)

# Action (Triggers execution)
filtered_df.show()

spark.stop()

from pyspark.sql import SparkSession
from pyspark.sql import functions as F

# Create Spark Session
spark = SparkSession.builder \
    .appName("Top5CitiesRevenue") \
    .getOrCreate()

# Load CSV
df = spark.read \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .csv("large_sales_data.csv")

# Top 5 cities by total revenue
top_5_cities = df.groupBy("city") \
    .agg(F.sum("revenue").alias("total_revenue")) \
    .orderBy(F.col("total_revenue").desc()) \
    .limit(5)

# Display result
top_5_cities.show()

spark.stop()

from pyspark.sql import SparkSession
import os

spark = SparkSession.builder.appName("ParquetVsCSV").getOrCreate()

df = spark.read.csv(
    "large_sales_data.csv",
    header=True,
    inferSchema=True
)

# Save as Parquet
df.write.mode("overwrite").parquet("sales_parquet")

# Compare sizes
csv_size = os.path.getsize("large_sales_data.csv") / 1024

parquet_size = sum(
    os.path.getsize(os.path.join(dp, f))
    for dp, dn, filenames in os.walk("sales_parquet")
    for f in filenames
) / 1024

print("CSV Size (KB):", round(csv_size, 2))
print("Parquet Size (KB):", round(parquet_size, 2))

spark.stop()

from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark = SparkSession.builder.appName("MedallionArchitecture").getOrCreate()

# Bronze Layer
bronze_df = spark.read.csv(
    "large_sales_data.csv",
    header=True,
    inferSchema=True
)

bronze_df.write.mode("overwrite").parquet("sales_bronze")

# Silver Layer
silver_df = bronze_df.dropDuplicates() \
                     .dropna()

silver_df.write.mode("overwrite").parquet("sales_silver")

# Gold Layer
gold_df = silver_df.groupBy("city") \
                   .agg(sum("revenue").alias("total_revenue"))

gold_df.write.mode("overwrite").parquet("sales_gold")

print("Bronze, Silver and Gold layers created successfully!")

spark.stop()

data_storage = {
    "Data Lake": {
        "Stores": "Structured, Semi-Structured, Unstructured Data",
        "Examples": "AWS S3, Azure Data Lake"
    },
    "Data Warehouse": {
        "Stores": "Structured Data Only",
        "Examples": "Snowflake, Amazon Redshift"
    }
}

for storage, details in data_storage.items():
    print("\n", storage)
    for key, value in details.items():
        print(f"{key}: {value}")