# -*- coding: utf-8 -*-
"""Day3-MiniProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1geQ8nFjFs6eFp0lKWXoNCCizLnkfi9Hf
"""

# ==========================================
# WEATHER DATA ETL PROJECT
# ==========================================
import requests
import pandas as pd

API_KEY = "YOUR_API_KEY"
CITY = "Chennai"

url = f"https://api.openweathermap.org/data/2.5/weather?q={CITY}&appid={API_KEY}&units=metric"

response = requests.get(url)

data = response.json()

print("Raw API Data:")
print(data)

# Check API success
if response.status_code == 200:

    weather_data = {
        "City": [data["name"]],
        "Temperature": [data["main"]["temp"]],
        "Humidity": [data["main"]["humidity"]],
        "Pressure": [data["main"]["pressure"]],
        "Weather": [data["weather"][0]["description"]],
        "Wind Speed": [data["wind"]["speed"]]
    }

    df = pd.DataFrame(weather_data)

    print("\nCleaned Data:")
    print(df)

    # Save CSV
    df.to_csv("weather_data.csv", index=False)

    print("\nCSV file saved successfully!")

else:
    print("\nError fetching data:")
    print(data["message"])

from google.colab import files
files.download("weather_data.csv")

# ==========================================
# EMPLOYEE SALARY ETL PROJECT
# ==========================================
import pandas as pd

df = pd.read_excel("employees.xlsx")

print("Original Data:")
print(df)

df = df.drop_duplicates()

df["Yearly_Salary"] = df["Monthly_Salary"] * 12

print("\nCleaned Data:")
print(df)

df.to_csv("cleaned_employee_salary.csv", index=False)

print("\nCSV file saved successfully!")

from google.colab import files
files.download("cleaned_employee_salary.csv")